### ISSUE TITLE
Raw Images + Raw IMU data + Calibration Parameters?

### ISSUE THREAD

**Issue by ArmandB** [MARSLab-UMN/vi_depth_completion#4]
Loved the work, especially since you guys used depth from a real SLAM algorithm! So many depth completion papers just only sample the ground truth depth.

Is it possible to get access to the dataset with raw images, IMU data, and calibration parameters to allow for experimentation with other SLAM algorithms?

Thank you for your time in advance.

**Comment by kouroshs** [comment]
Thank you for your kind words. All of us have graduated a few years ago and unfortunately don't have access to the original data used to generate the SLAM trajectories and feature tracks.

**Comment by ArmandB** [comment]
No worries, thanks for your time and all the best to you all!:D
